#Path for your local drive folder (absolute path)
drive_path: "~/Documents/drive"

#Add a list of file paths (relative to drive root) that should not be synced. Regexes are allowed
ignored_files: []

#If true, files that have been deleted locally will also be deleted on drive
allow_remote_deletion: true
#If true, the manifest will be re-written after each file. Slows down sync but prevents problems
immediate_rewrite: true

#Determines what will be done if a file has been edited locally and remotely
#keep_latest => Syncs whichever version has been edited last
#keep_remote => Downloads the remote version and overwrites local changes
#keep_local =>  Uploads the local version and overwrites remote changes
#ignore => Does nothing and keeps both versions
update_conflict_strategy: keep_latest

#Largest file size in megabytes that this program will handle. Anything larger than this will be ignored. Be careful about increasing this value as resumable upload has not been implemented yet
max_file_size: 1024

#Path for the file which keeps track of synced files (absolute path)
manifest_path: "~/.drivesync_manifest"
